import "./globals.css";
import { Inter } from "next/font/google";
import { QueryClientProvider } from "@tanstack/react-query";
import { ReactQueryProvider } from "./Provider/QueryClientProvider";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryProvider>
      <html lang="en">
        <body className="max-w-full bg-gray-800">
          <div className="mx-auto max-w-6xl flex flex-col h-full">
            <Navbar />
            {children}
          </div>
        </body>
      </html>
    </ReactQueryProvider>
  );
}
